%YAML:1.0
---
deviceType: Camera
K: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [ 1174.0, 0.0, 960.0,
          0.0, 1174.0, 540.0,
          0.0, 0.0, 1.0 ]
D: !!opencv-matrix
  rows: 5
  cols: 1
  dt: d
  data: [ 0.0, 0.0, 0.0, 0.0, 0.0 ]
r: !!opencv-matrix
  rows: 3
  cols: 1
  dt: d
  data: [ -0.20, 0.0, 0.0 ]
t: !!opencv-matrix
  rows: 3
  cols: 1
  dt: d
  data: [ 0.0, 0.0, 1.52 ]
sz: [1920, 1080]
remapped:
  []